feat: update scripts, make it possible to run scripts of type *_from_…
ocadotechnology/nexus-configurator pull request #14
Opened 2019-08-21 14:15 UTC by vivanov00

…list with proper parameters.

Will require improvements to documentation, to run the new scripts (v2.4.3) one must provide a lot more parameters as there has been significant drift.

2019-08-22 08:33 UTC, stuart-warren requested changes
few minor nits, otherwise looks good!

yet to validate

2019-08-22 08:33 UTC, stuart-warren commented on bin/nexus_configurator
> +                resp = nx.run_script_multi(script_type,resources)
nit: whitespace around comma

2019-08-22 08:33 UTC, stuart-warren commented on nexus_configurator/nexus.py
> +    def run_script_multi(self, script,arg):
nit: whitespace around comma

2019-08-22 08:33 UTC, stuart-warren commented on nexus_configurator/nexus.py
> +      return self._post(run_url, arg, content_type="text/plain")
nit: indentation for these lines inconsistent with rest of file

2019-08-22 08:46 UTC, vivanov00 commented
Nits - post-comma spacing and indentation for run_script_multi function body, fixed.

2019-08-22 13:07 UTC, vivanov00 commented
contrib/example_config.yaml updated.

2019-08-23 13:23 UTC, stuart-warren requested changes
`example_config.yaml` could probably be a lot shorter with fewer examples

No usage of `setup_users_from_list` which could be nice to use roles

everything works afaict

Otherwise looks good

2019-08-23 13:23 UTC, stuart-warren commented on contrib/example_config.yaml
> +      - maven-ocado-com
can we remove these `maven-ocado-com` repos, see line 140 too

I don't see them created, so was probably my bad from previous commit

2019-08-23 13:23 UTC, stuart-warren commented on bin/nexus_configurator
> +            if "list" in script_type:
I'd suggest this is: `if "_from_list" in script_type:`

2019-08-23 13:23 UTC, stuart-warren commented on bin/nexus_configurator
> +logging.basicConfig(level=logging.DEBUG)
so this is for requests?

I don't think debug really be the default

maybe something like this to set it dynamically https://github.com/ocadotechnology/cluster-location-webhook/blob/master/hook.py#L17-L22

2019-08-23 13:42 UTC, vivanov00 commented on contrib/example_config.yaml
> +      - maven-ocado-com
Yes, I shall remove them, and I agree on the shortness, but at the same time it is good to have lots of working examples.
Adding a setup_users_from_list section.

2019-08-23 13:45 UTC, vivanov00 commented on bin/nexus_configurator
> +logging.basicConfig(level=logging.DEBUG)
Just something for local testing I added and forgot to take out as it wasn't really a detriment in my view.
Adding a '--debug' param would be nice to have  as well.

2019-08-23 13:47 UTC, vivanov00 commented on bin/nexus_configurator
> +            if "list" in script_type:
Sure, there really isn't much of a danger of name collisions at the moment, but conciseness never hurts.

2019-08-25 06:36 UTC, stuart-warren approved these changes

2019-08-26 11:12 UTC, merged