Improve the docker image for nexus-configurator.
ocadotechnology/nexus-configurator pull request #7
Opened 2018-07-03 13:22 UTC by janrotter

This pull request introduces two changes. The first one instructs the nexus_configurator script to use the groovy scripts from pkg_resources, making it independent from the current working directory. The second commit adjusts the Dockerfile to use a multi-stage build (https://docs.docker.com/develop/develop-images/multistage-build/), allowing the image to be built with the Dockerfile only, so the dockerhub automatic builds can be used instead of Travis CI.

Please see the commit messages for more details.

2018-07-04 10:23 UTC, mikebryant commented
I would note that we aren't going to switch from Travis to dockerhub automated builds - that would remove the pre-merge testing we currently have. Doesn't mean we can't accept the changes though

2018-07-04 10:38 UTC, mikebryant commented
I think this is ok, but @stuart-warren can you take a look too?

2018-07-04 11:11 UTC, stuart-warren requested changes
other than that, LGTM

2018-07-04 11:11 UTC, stuart-warren commented on Dockerfile
> +RUN pip install .
this command doesn't obey the [Pipfile.lock](https://github.com/ocadotechnology/nexus-configurator/blob/master/Pipfile.lock) version of dependencies

2018-07-05 08:27 UTC, janrotter commented
@mikebryant What kind of testing are you referring to? I don't see any unit tests in the repository.

@stuart-warren Could you please take a look at the latest commit?

2018-07-05 13:23 UTC, stuart-warren requested changes

2018-07-05 13:23 UTC, stuart-warren commented on build.sh
> +ln -s ../nexus3-oss/files/groovy nexus_configurator/groovy
sorry, this won't work with the current travis build as travis currently calls this script and then builds the image

2018-07-05 13:32 UTC, mikebryant commented
@janrotter The basic testing that the docker build will work. Travis allows us to verify that prior to merge.

2018-07-06 08:33 UTC, stuart-warren approved these changes

2018-07-06 08:34 UTC, merged